services:
  server:
    build: ./fonts
    restart: always
    ports:
      - 8080:8080
    environment:
      DB_HOST: mysqldb
      DB_PORT: 3306
      DB_NAME: dipldb
      DB_USER: root
      DB_PASSWORD: majmun20
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:8.0
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: dipldb
      MYSQL_ROOT_PASSWORD: majmun20

  fonts-web:
    build: ./fonts-web
    ports:
      - 3000:3000
    stdin_open: true
    tty: true
